// include your scripts here 
$(window).on("load", function () {
@@include("./scripts/menu.js")
@@include("./scripts/slider.js")
@@include("./scripts/sizes.js")
@@include("./scripts/building.js")
@@include("./scripts/plintus.js")
@@include("./scripts/rake.js")
@@include("./scripts/trim.js")
@@include("./scripts/prices.js")
@@include("./scripts/range.js")
@@include("./scripts/popups.js")
@@include("./scripts/header.js")
@@include("./scripts/form.js")
})