// include your scripts here 
$(window).on("load", function () {
@@include("./scripts/menu.js")
@@include("./scripts/slider.js")
@@include("./scripts/sizes.js")
@@include("./scripts/product-utils.js")
@@include("./scripts/building.js")
@@include("./scripts/send-building.js")
@@include("./scripts/prices.js")
@@include("./scripts/board.js")
@@include("./scripts/french.js")
@@include("./scripts/hungarian.js")
@@include("./scripts/popups.js")
@@include("./scripts/header.js")
@@include("./scripts/range.js")
@@include("./scripts/form.js")
})